dist = "dist"

[build]
target = "srcs/leptos_app/index.html"
html_output = "index.html"
release = true              # Build in release mode.
public_url = "/"            # The public URL from which assets are to be served.
filehash = true             # Whether to include hash values in the output file names.
inject_scripts = true       # Whether to inject scripts (and module preloads) into the finalized output.
offline = false             # Run without network access
frozen = false              # Require Cargo.lock and cache are up to date
locked = false              # Require Cargo.lock is up to date
minify = "always"           # Control minification: can be one of: never, on_release, always
no_sri = false              # Allow disabling sub-resource integrity (SRI)

[clean]
cargo = false # Optionally perform a cargo clean.

[watch]
watch = []  # Paths to watch. The `build.target`'s parent folder is watched by default.
ignore = []

[serve]
addresses = ["127.0.0.1"]
port = 1421
aliases = ["http://localhost"] # The aliases to serve on.
open = false                   # Open a browser tab once the initial build is complete.
no_spa = false                 # Whether to disable fallback to index.html for missing files.
no_autoreload = false          # Disable auto-reload of the web app.
no_error_reporting = false     # Disable error reporting

[[proxy]]
backend = "ws://localhost:8081/socket.io"
ws = true                                 # Use WebSocket for this proxy
insecure = false                          # Disable certificate validation
no_system_proxy = false                   # Disable system proxy
# rewrite = ""                              # Strip the given prefix off paths
no_redirect = false                       # Disable following redirects of proxy responses
