config:
  ensure:
    maxErrorRate: 1
    max: 500
  variables:
    code: 28cf22c3-77e8-49f5-b2ef-fa3eb212cce3
  environments:
    dev:
      target: http://localhost:1420
      engines:
        playwright:
          launchOptions:
            headless: false
    ci:
      target: http://localhost:7777
      phases:
        # Create ramp up to 10 VUs per second
        - name: initial
          arrivalRate: 1
          rampTo: 10
          maxVusers: 10
          duration: 10
        # Creates 10 VUs every second
        - name: sustained
          arrivalRate: 1
          duration: 30
        - pause: 10
        # Creates 1 VU every second
        - name: stress
          arrivalRate: 5
          rampTo: 50
          maxVusers: 50
          duration: 30
    prod:
      target: https://spaced.fun
      phases:
        # Create ramp up to 10 VUs per second
        - name: initial
          arrivalRate: 1
          rampTo: 10
          maxVusers: 10
          duration: 10
        # Creates 10 VUs every second
        - name: sustained
          arrivalRate: 1
          duration: 30
        - pause: 10
        # Creates 1 VU every second
        - name: stress
          arrivalRate: 5
          rampTo: 50
          maxVusers: 50
          duration: 30
  processor: test.mjs
  engines:
    playwright:
      launchOptions:
        headless: true
scenarios:
  - engine: playwright
    testFunction: document_connections
