CREATE TABLE IF NOT EXISTS asset (
  id VARCHAR(16) PRIMARY KEY NOT NULL,
  name VARCHAR(100) NOT NULL,
  mime VARCHAR(100) NOT NULL,
  data BYTEA
);

CREATE TABLE IF NOT EXISTS item_assets (
  item_id INTEGER,
  asset_id VARCHAR(16),
  PRIMARY KEY (item_id, asset_id),
  FOREIGN KEY (item_id) REFERENCES item (id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (asset_id) REFERENCES asset (id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE item DROP COLUMN mime;
ALTER TABLE item DROP COLUMN file;
ALTER TABLE item DROP COLUMN name;
