networks:
  traefik-net:
    external: true

secrets:
  # Then run `docker secret create PROM_PASSSWORD web.yaml`
  # https://prometheus.io/docs/guides/basic-auth/
  # Create a `web.yaml` file with a hashed password (use `htpasswd -nB admin`) inside like this:
  # basic_auth_users:
  #   admin: $2b$12$hNf2lSsxfm0.i4a.1kVpSOVyBCfIB51VRjgBUyv6kdnyTlgWj81Ay
  #
  # Then run `docker secret create PROM_PASSSWORD web.yaml`
  PROM_PASSWORD:
    external: true

services:
  # Static file server
  nginx:
    image: ${REGISTRY:-ghcr.io}/ekhorn/spaced/nginx:${COMMIT_SHA:-latest}
    networks: [traefik-net]
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.${STACK_NAME}-nginx.rule=Host(`${SUBDOMAIN}.spaced.fun`) && PathPrefix(`/`)
        - traefik.http.services.${STACK_NAME}-nginx.loadbalancer.server.port=80
  # Spaced services
  item_socket:
    image: ${REGISTRY:-ghcr.io}/ekhorn/spaced/item_socket:${COMMIT_SHA:-latest}
    networks: [traefik-net]
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.${STACK_NAME}-item_socket.rule=Host(`${SUBDOMAIN}.spaced.fun`) && PathPrefix(`/socket.io`)
        - traefik.http.services.${STACK_NAME}-item_socket.loadbalancer.server.port=8081
        - traefik.http.services.${STACK_NAME}-item_socket.loadBalancer.sticky.cookie.name=server_id
        - traefik.http.services.${STACK_NAME}-item_socket.loadBalancer.sticky.cookie.httpOnly=true
    environment:
      - HOST=0.0.0.0
