scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: [cadvisor:8080]
  - job_name: traefik
    scrape_interval: 5s
    static_configs:
      - targets: [traefik:8080]
  - job_name: item_socket
    scrape_interval: 5s
    static_configs:
      - targets: [item_socket:8081]
