[package]
name = "spaced"
version.workspace = true
description = "Desktop app for Spaced"
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
anyhow.workspace = true
tauri = { version = "1", features = ["dialog"] }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
tokio.workspace = true
serde.workspace = true
tracing.workspace = true
thiserror.workspace = true
utils = { path = "../utils", features = ["logging"] }
candle-core = "0.4.1"
candle-onnx = "*"
image = "*"
# tch = "0.15.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
