name: build
on: workflow_call

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  SQLX_OFFLINE: true

jobs:
  tsc:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npx --workspaces tsc -b

  udeps:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libayatana-appindicator3-dev protobuf-compiler
          rustup set auto-self-update disable
          rustup default nightly
          mkdir dist
      - uses: taiki-e/install-action@cargo-udeps
      - run: cargo udeps
      - run: cargo udeps --all-features
