name: e2e
on: workflow_call

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - if: ${{ github.ref_type == 'branch' && github.ref_name != 'main' }}
        run: echo "PR_NUMBER=$(git name-rev HEAD --name-only | cut -d'/' -f3)" >> $GITHUB_ENV
      - run: npm ci
      - run: npx playwright@1.50.1 install --with-deps
      - run: npm run e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: srcs/e2e/playwright-report/
          retention-days: 30
