name: Deploy Workflow

on:
  workflow_dispatch:

jobs:
  test_servers:
    runs-on: ubuntu-latest
    needs: publish
    timeout-minutes: 20
    concurrency:
      group: ${{ matrix.subdomain }}
    strategy:
      matrix:
        subdomain: [aws, do, hetzner]
        # gc, ionos
    environment:
      name: test/${{ matrix.subdomain }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "COMMIT_SHA=${{ github.sha }}" >> .env
          echo "SUBDOMAIN=${{ matrix.subdomain }}" >> .env
      - uses: ./.github/actions/docker_stack
        with:
          args: deploy ${{ matrix.subdomain }} -c config/docker/test-stack.yaml
          host: ${{ matrix.subdomain }}.spaced.fun
          user: spaced
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          env_file: .env

  # load_test:
  #   runs-on: self-hosted
  #   needs: test_servers
  #   timeout-minutes: 20
  #   concurrency:
  #     group: ${{ matrix.subdomain }}
  #   strategy:
  #     matrix:
  #       subdomain: [aws, do, hetzner]
  #       # gc, ionos
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: artilleryio/action-cli@v1
  #       with:
  #         command: run config/load/socket-io.yml ${{ matrix.subdomain }}.spaced.fun
  #     # - run: ssh spaced@${{ matrix.subdomain }}.spaced.fun
