name: review

on:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    uses: ./.github/workflows/fmt.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  build:
    uses: ./.github/workflows/build.yaml

  test:
    uses: ./.github/workflows/test.yaml

  publish:
    uses: ./.github/workflows/publish.yaml
    permissions:
      packages: write
    secrets: inherit
    with:
      registry: ghcr.io
      username: ${{ github.actor }}

  docker_scout:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: publish
    permissions:
      pull-requests: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations,sbom #,environment,compare
          dockerhub-user: ekhorn
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: ghcr.io/ekhorn/spaced/item_socket:${{ github.sha }}
          # ghcr.io/ekhorn/spaced/nginx:${{ github.sha }}
          to: ghcr.io/ekhorn/spaced/item_socket:latest
          registry-user: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }} # to be able to write the comment

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    timeout-minutes: 20
    environment:
      name: review-${{ github.event.number }}
      url: https://${{ github.event.number }}.review.spaced.fun
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_OUTPUT
          echo "COMMIT_SHA=${{ github.sha }}" >> .env
          echo "LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}" >> .env
          echo "STACK_NAME=review-${{ github.event.number }}" >> .env
          echo "SUBDOMAIN=${{ github.event.number }}.review" >> .env
      - uses: ./.github/actions/docker_stack
        with:
          args: |
            deploy review-${{ github.event.number }} -c config/docker/services-stack.yaml
            deploy root -c config/docker/root-stack.yaml
          host: review.spaced.fun
          user: spaced
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          env_file: .env

  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: provision
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV
      - run: npx @lhci/cli@0.14 autorun --config config/lighthouserc.cjs
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  e2e:
    needs: provision
    uses: ./.github/workflows/e2e.yaml

  test_servers:
    runs-on: ubuntu-latest
    needs: publish
    timeout-minutes: 20
    concurrency:
      group: ${{ matrix.subdomain }}
    strategy:
      matrix:
        subdomain: [aws, do, hetzner]
        # gc, ionos
    environment:
      name: test/${{ matrix.subdomain }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "COMMIT_SHA=${{ github.sha }}" >> .env
          echo "SUBDOMAIN=${{ matrix.subdomain }}" >> .env
      - uses: ./.github/actions/docker_stack
        with:
          args: deploy ${{ matrix.subdomain }} -c config/docker/test-stack.yaml
          host: ${{ matrix.subdomain }}.spaced.fun
          user: spaced
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          env_file: .env

  # load_test:
  #   runs-on: self-hosted
  #   needs: test_servers
  #   timeout-minutes: 20
  #   concurrency:
  #     group: ${{ matrix.subdomain }}
  #   strategy:
  #     matrix:
  #       subdomain: [aws, do, hetzner]
  #       # gc, ionos
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: artilleryio/action-cli@v1
  #       with:
  #         command: run config/load/socket-io.yml ${{ matrix.subdomain }}.spaced.fun
  #     # - run: ssh spaced@${{ matrix.subdomain }}.spaced.fun

  # cleanup:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 20
  #   if: github.event_name == pull_request && github.event.action == closed
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/docker_stack
  #       with:
  #         args: rm review-${{ github.event.number }}
  #         host: review.spaced.fun
  #         user: spaced
  #         ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         env_file: .env
